In [1]:
import cv2
import numpy as np
from PIL import Image

In [2]:
img=cv2.imread('ex_pic.png',0)
print(img.shape) # 顯示 2 Dim 圖片的緯度 row=15 , col=16
display(Image.open('ex_pic.png'))
print(img[:][:])# 以陣列表現每一點的灰階值 (0~255 )

(15, 16)


[[  0   0   0   0   0   0   0  11   4 227 254 255 255 255 255 255]
 [  0   0   0   0   0   0   0  11   4 227 254 255 255 255 255 255]
 [  0   0   0   0   0   0   0  11   4 227 254 255 255 255 255 255]
 [  0   0   0   0   0   0   0  11   4 227 254 255 255 255 255 255]
 [  0   0   0   0   0   0   0  11   4 227 254 255 255 255 255 255]
 [  0   0   0   0   0   0   0  11   4 227 254 255 255 255 255 255]
 [  0   0   0   0   0   0   0  11   4 227 254 255 255 255 255 255]
 [ 27  27  27  27  27  27  27  32   7 225 254 253 253 253 253 253]
 [ 48  48  48  48  48  48  48  48  46 211 232 231 231 231 231 231]
 [219 219 219 219 219 219 219 219 215  84  58  57  57  57  57  57]
 [254 254 254 254 254 254 254 254 247  70  18  31  30  30  30  30]
 [255 255 255 255 255 255 255 254 247  66   7   3   1   1   1   1]
 [255 255 255 255 255 255 255 254 248  66   7   2   0   0   0   0]
 [255 255 255 255 255 255 255 254 248  66   7   2   0   0   0   0]
 [255 255 255 255 255 255 255 254 248  66   7   2   0   0   0 

In [8]:
img[:5][:]=255  # 修改前5列變成 白色
print(img)

[[255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255]
 [255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255]
 [255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255]
 [255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255]
 [255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255]
 [  0   0   0   0   0   0   0  11   4 227 254 255 255 255 255 255]
 [  0   0   0   0   0   0   0  11   4 227 254 255 255 255 255 255]
 [ 27  27  27  27  27  27  27  32   7 225 254 253 253 253 253 253]
 [ 48  48  48  48  48  48  48  48  46 211 232 231 231 231 231 231]
 [219 219 219 219 219 219 219 219 215  84  58  57  57  57  57  57]
 [254 254 254 254 254 254 254 254 247  70  18  31  30  30  30  30]
 [255 255 255 255 255 255 255 254 247  66   7   3   1   1   1   1]
 [255 255 255 255 255 255 255 254 248  66   7   2   0   0   0   0]
 [255 255 255 255 255 255 255 254 248  66   7   2   0   0   0   0]
 [255 255 255 255 255 255 255 254 248  66   7   2   0   0   0 

In [4]:
cv2.imshow('logo',img)
cv2.waitKey(0)
cv2.destroyAllWindows()